### ISSUE TITLE
Bug in bash2py.py

### ISSUE THREAD

**Issue by aalbino2** [clarity20/bash2py#3]
at line 17 the indentation is incorrectly made of 8 spaces instead of 1 tab

```python
        if (lth == 1):
```

**Comment by clarity20** [comment]
All indentation is set to tabs as of commit # b02fe76. Closing this issue.

**Comment by verhovsky** [comment]
The indentation should be configurable. 4 spaces is much more common for Python code.

https://verhovs.ky/tabs-or-spaces/ (or the original: https://ukupat.github.io/tabs-or-spaces/ )
