### ISSUE TITLE
While installing ""bash2pyengine  No such file or directory""

### ISSUE THREAD

**Issue by alarsalars** [clarity20/bash2py#34]
make: *** [Makefile:618: y.tab.c] Error 127
ls: cannot access 'bash2pyengine': No such file or directory

**Comment by alarsalars** [comment]
Fix by running those 2 commands

sudo apt-get install bison -y
sudo apt-get install byacc -y

**Comment by clarity20** [comment]
It's not clear what you're saying here. Did your build break on line 618 of the Makefile and you fixed it by installing `bison` and `byacc`? But from issue #35 it looks like you eventually got the project to build. So let's focus on that issue for the time being.

**Comment by rustytravis** [comment]
I'm getting a similar result:
`~/src/bash2py$ ./install
...
rm -f burp.o
gcc  -DPROGRAM='"bash"' -DCONF_HOSTTYPE='"x86_64"' -DCONF_OSTYPE='"linux-gnu"' -DCONF_MACHTYPE='"x86_64-unknown-linux-gnu"' -DCONF_VENDOR='"unknown"' -DLOCALEDIR='"/usr/local/share/locale"' -DPACKAGE='"bash"' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib    -g -O2  -c burp.c
burp.c: In function ‘_build_log_entry’:
burp.c:326:24: error: invalid initializer
  326 |         va_list args = *pArgs;
      |                        ^
make: *** [Makefile:98: burp.o] Error 1
ls: cannot access 'bash2pyengine': No such file or directory

~/src/bash2py$ find . -name \*bash2pyengine\*
~/src/bash2py$`

How to remedy, please?

**Comment by ltspicer** [comment]
Same issue here. "burp.c:326:24: error: invalid initializer"

OS:
Linux Mint 22 mate
