### ISSUE TITLE
Compilation issue and segfault

### ISSUE THREAD

**Issue by Lecrapouille** [clarity20/bash2py#7]
Even if I modify the Makefile this code is regenerated:
```
bash2pyengine: .made
	mv bash bash2pyengine
	cp bash2pyengine ~/bin/bash2pyengine
```

Better to add `mkdir -p ~/bin` to be sure the folder is present else this failed.

Else like other issues:
```
 ~/bin/bash2pyengine 
Erreur de segmentation
```

**Comment by clarity20** [comment]
Thanks for the heads-up. I've added this safeguard to `Makefile.in` (the makefile template). Please resync and rerun `configure` for a clean `Makefile`.
